'use client';

import { useEffect, useMemo, useState } from 'react';

type AssessmentSummary = { assessment_id: string; source_name?: string | null; imported_at?: string | null; finding_count: number };
type Finding = { check_id?: string; workload?: string; category?: string; status?: string; severity?: string; title?: string; evidence?: unknown; recommendation?: unknown };
type FindingsPayload = { assessment_id: string; source_name?: string | null; imported_at?: string | null; findings: Finding[] };
type WorkflowItem = Finding & { assessmentId: string; sourceName: string; importedAt?: string | null; workloadName: string };

function workloadFromName(name: string) {
  const value = name.toLowerCase();
  if (value.includes('exchange')) return 'Exchange Online'; if (value.includes('entra')) return 'Entra ID';
  if (value.includes('sharepoint')) return 'SharePoint Online'; if (value.includes('onedrive')) return 'OneDrive';
  if (value.includes('teams')) return 'Teams'; if (value.includes('intune')) return 'Intune';
  if (value.includes('defender')) return 'Defender'; if (value.includes('purview')) return 'Microsoft Purview'; return 'TenantIQ';
}
function text(value: unknown) { if (value === null || value === undefined || value === '') return ''; if (typeof value === 'string') return value; try { return JSON.stringify(value); } catch { return String(value); } }
async function json(response: Response) { const body = await response.text(); if (!body) return null; try { return JSON.parse(body); } catch { throw new Error('TenantIQ received an unexpected workflow response.'); } }
const severityOrder: Record<string, number> = { critical: 0, high: 1, medium: 2, low: 3, none: 4, '': 5 };
const statusOrder: Record<string, number> = { FAIL: 0, WARNING: 1 };

export default function TenantIQWorkflow() {
  const [items, setItems] = useState<WorkflowItem[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const [workload, setWorkload] = useState('ALL'); const [priority, setPriority] = useState('ALL'); const [expanded, setExpanded] = useState<string | null>(null);

  useEffect(() => { let cancelled = false; async function load() { try {
    const assessmentsResponse = await fetch('/api/assistant/assessments', { cache: 'no-store' }); const assessmentsPayload = await json(assessmentsResponse);
    if (!assessmentsResponse.ok) throw new Error(assessmentsPayload?.detail || 'Unable to load assessments for workflow.');
    const assessments = (Array.isArray(assessmentsPayload) ? assessmentsPayload : []) as AssessmentSummary[]; const latest = new Map<string, AssessmentSummary>();
    for (const assessment of assessments) { const w = workloadFromName(assessment.source_name || assessment.assessment_id); const current = latest.get(w); const a = assessment.imported_at ? new Date(assessment.imported_at).getTime() : 0; const b = current?.imported_at ? new Date(current.imported_at).getTime() : 0; if (!current || a >= b) latest.set(w, assessment); }
    const payloads = await Promise.all([...latest.values()].map(async a => { const r = await fetch(`/api/assistant/assessments/${encodeURIComponent(a.assessment_id)}/findings`, { cache: 'no-store' }); const p = await json(r); if (!r.ok) throw new Error(p?.detail || 'Unable to load workflow findings.'); return p as FindingsPayload; }));
    const actionable: WorkflowItem[] = []; for (const p of payloads) { const sourceName = p.source_name || p.assessment_id; const workloadName = workloadFromName(sourceName); for (const finding of p.findings || []) { const status = String(finding.status || '').toUpperCase(); if (status === 'FAIL' || status === 'WARNING') actionable.push({ ...finding, assessmentId: p.assessment_id, sourceName, importedAt: p.imported_at, workloadName }); } }
    actionable.sort((a,b) => { const s=(severityOrder[String(a.severity||'').toLowerCase()]??9)-(severityOrder[String(b.severity||'').toLowerCase()]??9); if(s)return s; const st=(statusOrder[String(a.status||'').toUpperCase()]??9)-(statusOrder[String(b.status||'').toUpperCase()]??9); if(st)return st; return String(a.check_id||'').localeCompare(String(b.check_id||'')); }); if(!cancelled)setItems(actionable);
  } catch(err){ if(!cancelled)setError(err instanceof Error?err.message:'Unable to build the TenantIQ remediation workflow.'); } finally { if(!cancelled)setLoading(false); } } load(); return()=>{cancelled=true}; },[]);

  const workloads=useMemo(()=>['ALL',...Array.from(new Set(items.map(i=>i.workloadName))).sort()],[items]);
  const filtered=useMemo(()=>items.filter(i=>(workload==='ALL'||i.workloadName===workload)&&(priority==='ALL'||String(i.severity||'').toLowerCase()===priority.toLowerCase())),[items,workload,priority]);
  const high=items.filter(i=>['critical','high'].includes(String(i.severity||'').toLowerCase())).length; const fails=items.filter(i=>String(i.status||'').toUpperCase()==='FAIL').length; const warnings=items.length-fails;
  if(loading)return <div style={panelStyle}>Building your remediation workflow from the latest stored assessments…</div>; if(error)return <div style={{...panelStyle,borderColor:'rgba(255,90,90,.28)',color:'#ffaaaa'}}>{error}</div>;

  return <>
    <div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(150px,1fr))',gap:12,marginBottom:18}}><Metric label="Actionable" value={String(items.length)}/><Metric label="Fail" value={String(fails)} tone="fail"/><Metric label="Warning" value={String(warnings)} tone="warning"/><Metric label="High / Critical" value={String(high)} tone={high?'warning':'normal'}/><Metric label="Workloads affected" value={String(new Set(items.map(i=>i.workloadName)).size)}/></div>
    <section style={{...panelStyle,marginBottom:16}}><div style={{color:'#6eb5ff',fontSize:11,fontWeight:900,letterSpacing:'.06em',textTransform:'uppercase',marginBottom:12}}>Remediation lifecycle</div><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(170px,1fr))',gap:10}}><Step number="1" title="Review evidence" text="Confirm exactly what TenantIQ observed." active/><Step number="2" title="Remediate" text="Apply the approved configuration change."/><Step number="3" title="Validate" text="Verify the intended Microsoft 365 state."/><Step number="4" title="Re-assess" text="Run TenantIQ again and confirm it clears."/></div></section>
    <div style={{...panelStyle,marginBottom:16,display:'flex',justifyContent:'space-between',gap:12,alignItems:'center',flexWrap:'wrap'}}><div><div style={{color:'#6eb5ff',fontSize:11,fontWeight:900,letterSpacing:'.06em',textTransform:'uppercase'}}>Remediation queue</div><div style={{color:'#aeb8c8',fontSize:13,marginTop:5}}>{filtered.length} finding{filtered.length===1?'':'s'} shown · latest assessment per workload · highest risk first</div></div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><select value={priority} onChange={e=>setPriority(e.target.value)} style={selectStyle}><option value="ALL">All severities</option><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select><select value={workload} onChange={e=>setWorkload(e.target.value)} style={selectStyle}>{workloads.map(n=><option key={n} value={n}>{n==='ALL'?'All workloads':n}</option>)}</select></div></div>
    {!filtered.length?<div style={panelStyle}>No actionable findings match the current workflow filters.</div>:<div style={{display:'grid',gap:10}}>{filtered.map((item,index)=>{const id=`${item.assessmentId}-${item.check_id||index}`; const open=expanded===id; const status=String(item.status||'WARNING').toUpperCase(); const evidence=text(item.evidence)||'No detailed evidence was supplied for this finding.'; const recommendation=text(item.recommendation)||'Review the associated TenantIQ guidance before making a configuration change.'; const assessmentHref=`/assessments/${encodeURIComponent(item.assessmentId)}#${encodeURIComponent(item.check_id||'')}`; const question=`Walk me through remediation and validation for ${item.check_id||item.title||'this finding'} using the selected assessment evidence.`; const assistantHref=`/api/assistant/select-assessment?assessment=${encodeURIComponent(item.assessmentId)}&question=${encodeURIComponent(question)}`; return <article key={id} style={{...panelStyle,padding:0,overflow:'hidden'}}><button onClick={()=>setExpanded(open?null:id)} style={rowButtonStyle}><div style={{minWidth:145}}><div style={{color:'#79baff',fontSize:10,fontWeight:900,textTransform:'uppercase',letterSpacing:'.05em'}}>{item.workloadName}</div><div style={{fontWeight:900,marginTop:4}}>{item.check_id||'Finding'}</div></div><div style={{flex:'1 1 300px',textAlign:'left'}}><div style={{fontWeight:800,color:'#edf5ff'}}>{item.title||'TenantIQ finding'}</div><div style={{fontSize:11,color:'#758ba3',marginTop:4}}>{item.category||'Assessment control'}</div></div><div style={{display:'flex',alignItems:'center',gap:8}}><StatusPill status={status}/>{item.severity&&<span style={{fontSize:12,color:'#a4b4c6'}}>{item.severity}</span>}<span style={{color:'#79baff',fontSize:18}}>{open?'−':'+'}</span></div></button>{open&&<div style={{padding:'0 18px 18px',borderTop:'1px solid rgba(86,160,255,.12)'}}><div style={{display:'grid',gridTemplateColumns:'repeat(auto-fit,minmax(280px,1fr))',gap:16,paddingTop:16}}><Field label="Observed evidence" value={evidence}/><Field label="Recommended remediation" value={recommendation}/></div><div style={{marginTop:16,padding:14,borderRadius:12,background:'rgba(47,135,255,.055)',border:'1px solid rgba(86,160,255,.12)'}}><div style={{fontSize:11,fontWeight:900,color:'#7fbaff',textTransform:'uppercase',letterSpacing:'.05em'}}>Completion criteria</div><div style={{fontSize:13,color:'#b8c5d3',lineHeight:1.6,marginTop:5}}>Apply the approved change, validate the configuration, then re-run this workload assessment. Treat the item as resolved only when TenantIQ no longer reports the FAIL or WARNING state.</div></div><div style={{display:'flex',gap:8,marginTop:16,flexWrap:'wrap'}}><a href={assessmentHref} style={secondaryLinkStyle}>View assessment evidence</a><a href={assistantHref} style={primaryLinkStyle}>Start guided remediation →</a></div></div>}</article>})}</div>}
  </>;
}
function Step({number,title,text:description,active=false}:{number:string;title:string;text:string;active?:boolean}){return <div style={{border:`1px solid ${active?'rgba(47,135,255,.4)':'rgba(86,160,255,.14)'}`,borderRadius:12,padding:14,background:active?'rgba(47,135,255,.08)':'rgba(6,17,31,.42)'}}><div style={{color:'#6eb5ff',fontSize:11,fontWeight:900}}>STEP {number}</div><div style={{color:'#eef5fd',fontSize:15,fontWeight:850,marginTop:5}}>{title}</div><div style={{color:'#8fa2b8',fontSize:12,lineHeight:1.5,marginTop:5}}>{description}</div></div>}
function Field({label,value}:{label:string;value:string}){return <div><div style={{color:'#7f93aa',fontSize:11,fontWeight:900,textTransform:'uppercase',letterSpacing:'.06em',marginBottom:5}}>{label}</div><div style={{color:'#c6d3e2',lineHeight:1.6,fontSize:13,whiteSpace:'pre-wrap'}}>{value}</div></div>}
function StatusPill({status}:{status:string}){const fail=status==='FAIL';return <span style={{borderRadius:999,padding:'4px 8px',background:fail?'rgba(255,90,90,.10)':'rgba(244,196,48,.09)',color:fail?'#ff9b9b':'#f4d35e',fontSize:10,fontWeight:900}}>{status}</span>}
function Metric({label,value,tone='normal'}:{label:string;value:string;tone?:string}){const color=tone==='fail'?'#ff8f8f':tone==='warning'?'#f4d35e':'#f3f7fc';return <div style={{border:'1px solid rgba(86,160,255,.17)',borderRadius:14,background:'rgba(8,22,40,.66)',padding:15}}><div style={{color:'#8192a6',fontSize:10,fontWeight:900,textTransform:'uppercase',letterSpacing:'.06em'}}>{label}</div><div style={{color,fontSize:25,fontWeight:900,marginTop:6}}>{value}</div></div>}
const panelStyle={border:'1px solid rgba(86,160,255,.18)',borderRadius:16,background:'rgba(8,22,40,.72)',padding:18,color:'#dce7f4'};
const selectStyle={border:'1px solid rgba(86,160,255,.22)',borderRadius:10,background:'#081425',color:'#edf5ff',padding:'10px 12px',outline:'none'};
const rowButtonStyle={width:'100%',border:0,background:'transparent',color:'inherit',padding:18,display:'flex',gap:18,alignItems:'center',flexWrap:'wrap',cursor:'pointer',textAlign:'left' as const};
const primaryLinkStyle={display:'inline-block',borderRadius:10,padding:'10px 13px',background:'#2f87ff',color:'#fff',fontSize:12,fontWeight:850,textDecoration:'none',whiteSpace:'nowrap' as const};
const secondaryLinkStyle={display:'inline-block',borderRadius:10,padding:'9px 12px',border:'1px solid rgba(86,160,255,.26)',color:'#8fc7ff',fontSize:12,fontWeight:850,textDecoration:'none',whiteSpace:'nowrap' as const};